// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXa7pPMHnSP3bVvKkYYwWmAlFIDF_f1rg',
    appId: '1:14354973937:web:6cf730588a998d2d4b9550',
    messagingSenderId: '14354973937',
    projectId: 'foood-f27e7',
    authDomain: 'foood-f27e7.firebaseapp.com',
    storageBucket: 'foood-f27e7.firebasestorage.app',
    measurementId: 'G-BHW12ZF857',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhuyja3BY121_CS3NwGn-xYnlzQED6AAE',
    appId: '1:14354973937:android:6a6d946bd81c2f7b4b9550',
    messagingSenderId: '14354973937',
    projectId: 'foood-f27e7',
    storageBucket: 'foood-f27e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDVYtCZcSiBzurVUUE6tbZRqUX5RiFlVI',
    appId: '1:14354973937:ios:f9826ff3c419005c4b9550',
    messagingSenderId: '14354973937',
    projectId: 'foood-f27e7',
    storageBucket: 'foood-f27e7.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDVYtCZcSiBzurVUUE6tbZRqUX5RiFlVI',
    appId: '1:14354973937:ios:f9826ff3c419005c4b9550',
    messagingSenderId: '14354973937',
    projectId: 'foood-f27e7',
    storageBucket: 'foood-f27e7.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXa7pPMHnSP3bVvKkYYwWmAlFIDF_f1rg',
    appId: '1:14354973937:web:902e7b2be894c5734b9550',
    messagingSenderId: '14354973937',
    projectId: 'foood-f27e7',
    authDomain: 'foood-f27e7.firebaseapp.com',
    storageBucket: 'foood-f27e7.firebasestorage.app',
    measurementId: 'G-ZT9C3KW6L1',
  );
}
